version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for main toml file.
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      dependency-type: "all"
  # Maintain dependencies for individual packages
  - package-ecosystem: "cargo"
    directory: "/environment-monitor"
    schedule:
      interval: "daily"
    allow:
      dependency-type: "all"
  - package-ecosystem: "cargo"
    directory: "/veml7700"
    schedule:
      interval: "daily"
    allow:
      dependency-type: "all"
